<?php 
if(!isset($_POST['verbose'])) $verbose = "false"; else $verbose = $_POST['verbose'];

function dbquery($query) {
global $conn, $mode, $verbose;
if($verbose == "true") echo $query."<br>";
$res = @mysqli_query($conn, $query); 
if(!$res) { 
  $error = mysqli_error($conn);
  $full_error = "<p>MySQL error ".mysqli_errno($conn).": ".$error."<br>Generated by URL '".$_SERVER["PHP_SELF"]."'<br>with Query '".$query."' <p>";
  if((mysqli_errno($conn) == "1062") && (strpos($query, "specific_price") > 0))
  { echo "<br>Index 2 of the 'specific_price' table contains the following fields: id_product,id_shop,id_shop_group,id_currency,id_country,id_group,id_customer,id_product_attribute,from_quantity,from,to";
  }
  if($mode == "background") colordie($full_error);
  else colordie($full_error);
}
return $res;
}

$selected_img_extension = "";
function get_image_extension($id_image, $type)
{ global $selected_img_extension, $img_extensions, $triplepath;
  if($selected_img_extension == "")
  { if($type == "category")
    { foreach($img_extensions AS $ipart)
      { $fff = $triplepath.'img/c/'.$id_image.$ipart;
	    if(file_exists($fff))
	      $selected_img_extension = $ipart;
      }	 
	}
	else // type=product
    { foreach($img_extensions AS $ipart)
      { $fff = $triplepath.'img/p'.getpath($id_image).'/'.$id_image.$ipart;
	    if(file_exists($fff))
	      $selected_img_extension = $ipart;
      }	  
	}
  }
  return $selected_img_extension;
}

function get_product_image($id_image, $imagelist) /* returns link or "X" */
{ global $selected_img_extension;
  if(($id_image == 0) || ($id_image == ""))
    return "X";
  get_image_extension($id_image, "product");
  $base_uri = get_base_uri();
  if($selected_img_extension != "")
    return '<a href="'.$base_uri.'img/p'.getpath($id_image).'/'.$id_image.'.jpg" target="_blank" title="'.$id_image.';'.$imagelist.'"><img src="'.$base_uri.'img/p'.getpath($id_image).'/'.$id_image.$selected_img_extension.'" width="45px" height="45px" /></a>';
	
  return "xx";
}

/* getpath() takes a string like "189" and returns something like "/1/8/9" */
function getpath($name)
{ $str = "";
  for ($i=0; $i<strlen($name); $i++)
  { $str .= "/".$name[$i];
  }
  return $str;
}

function get_rewrite_settings()
{ $query="select value from ". _DB_PREFIX_."configuration";
  $query .= " WHERE name='PS_REWRITING_SETTINGS'";
  $res=dbquery($query);
  $row = mysqli_fetch_array($res);
  return $row['value'];
}

function get_base_uri()
{ global $id_shop;
  if(isset($id_shop) && ($id_shop != ""))
  { $query="select physical_uri from ". _DB_PREFIX_."shop_url";
    $query .= " WHERE id_shop='".$id_shop."'";
    $res=dbquery($query);
    if(mysqli_num_rows($res) != 0)
	{ $row = mysqli_fetch_array($res);
	  return $row["physical_uri"];
	}
  }
  if(_PS_VERSION_ >= "1.5")
  { $query="select physical_uri from ". _DB_PREFIX_."shop_url";
    $res=dbquery($query);
    if(mysqli_num_rows($res) != 0)
	{ $row = mysqli_fetch_array($res);
	  return $row["physical_uri"];
	}
  }
  $query="select value from ". _DB_PREFIX_."configuration";
  $query .= " WHERE name='__PS_BASE_URI__'";
  $res=dbquery($query);
  if(mysqli_num_rows($res) != 0)
  { $row = mysqli_fetch_array($res);
    return $row['value'];
  }
  if(defined("_PS_DIRECTORY_"))
    return _PS_DIRECTORY_;
  return "WATA";
}
  
function colordie($text)
{ echo "<script>setTimeout('document.body.bgColor=\'#44eecc\';',200);

function inIframe () {
    try {
        return window.self !== window.top;
    } catch (e) {
        return true;
    }
}
 if(inIframe ())
{alert('".str_replace("'","\\'",$text)."');}
 </script>"; /* page must be complete before this works */
  die($text);
}

/* addspaces adds spaces to the begin of numbers  */
function addspaces($source) { 
  if($source == "") return "";
  $source = ltrim($source); /* remove leading spaces */
  for($i=0; $i<strlen($source); $i++)
    if(!is_numeric($source[$i]))
      break;
  $spaces = "";
  for(;$i<4;$i++) $spaces=$spaces." ";
  return $spaces.$source;
}

function check_mysql_date($mydate)
{ $parts = explode("-", $mydate);
  if(sizeof($parts) != 3) return false;
  return(checkdate($parts[1],$parts[2],$parts[0]));
}

function print_menubar()
{ echo '<div class="menuBar" id="mainmenu" onmouseover="menuinit()">
 <a name="prodBtn" href="product-edit.php" >Product Edit</a>
 <a name="sortBtn" href="product-sort.php" >Product Sort</a>
 <a name="catBtn" href="cat-edit.php">Category Edit</a>
 <a name="orderBtn" href="order-edit.php">Order Edit</a>
 <a name="toolsBtn" href="discount-list.php">Tools and stats</a>
 <a name="logoutBtn" href="logout1.php">Logout</a></div>';
}
